project_id = "yhmtiileawdvaqlnwfbr"

[functions.auth-login]
verify_jwt = false

[functions.auth-verify-session]
verify_jwt = false

[functions.auth-get-users]
verify_jwt = false

[functions.auth-add-user]
verify_jwt = false

[functions.auth-update-user]
verify_jwt = false

[functions.auth-delete-user]
verify_jwt = false

[functions.training-schedules-manage]
verify_jwt = false
